name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "v1.x"
      - name: Check fmt
        run: deno fmt --check
      - name: Run lint
        run: deno lint
      - name: Run type check
        run: deno check --remote *.ts
      - name: Run test
        run: deno test